<?php

module_load_include('inc', 'nefo', 'includes/nefo.admin.institutions');
module_load_include('inc', 'nefo', 'includes/nefo.search');

/**
 * @file
 * Internationalization (i18n) submodule: Multilingual NeFo categories
 */

/**
 * Implements hook_menu().
 *
 * Add translate tab to categories config.
 */
function i18n_nefo_topic_menu() {
  $items['admin/config/nefo/categories/topics/%nefo_topic/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -100,
  );
  $items['admin/config/nefo/categories/topics/%nefo_topic/translate'] = array(
    'title' => 'Translate',
    'access callback' => 'i18n_nefo_topic_translate_tab_access',
    'page callback' => 'i18n_string_object_translate_page',
    'page arguments' => array('nefo_topic', 5),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );
  $items['admin/config/nefo/categories/topics/%nefo_topic/translate/%language'] = array(
    'title' => 'Translate',
    'access callback' => 'i18n_nefo_topic_translate_tab_access',
    'page callback' => 'i18n_string_object_translate_page',
    'page arguments' => array('nefo_topic', 5, 7),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Menu access callback function.
 */
function i18n_nefo_topic_translate_tab_access() {
  return user_access('administer nefo configuration');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function i18n_nefo_topic_form_nefo_admin_topic_delete_confirm_alter(&$form, &$form_state) {
  $form['#submit'][] = 'i18n_nefo_topic_form_nefo_admin_topic_delete_confirm_submit';
}

/**
 * Remove strings for deleted categories.
 */
function i18n_nefo_topic_form_nefo_admin_topic_delete_confirm_submit(&$form, $form_state) {
  $tid = $form['tid']['#value']['tid'];
  i18n_string_remove("nefo_topic:topic:$tid:name");
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function i18n_nefo_topic_form_nefo_admin_topic_form_alter(&$form, &$form_state) {
    $form['actions']['translate'] = array(
    '#type' => 'submit',
    '#name'   => 'save_translate',
    '#value' => t('Save and translate'),
  );
  $form['#submit'][] = 'i18n_nefo_topic_form_nefo_admin_topic_form_submit';
}

/**
 * Remove strings for edited/added topic.
 */
function i18n_nefo_topic_form_nefo_admin_topic_form_submit($form, &$form_state) {
  $topic = $form_state['values'];
  i18n_string_update(array('nefo_topic', 'topic', $topic['tid'], 'name'), $topic['name']);
  if ($form_state['triggering_element']['#name'] == 'save_translate') {
    $form_state['redirect'] = 'admin/config/nefo/categories/topics/' . $topic['tid'] . '/translate';
  }
}


