<?php

module_load_include('inc', 'nefo', 'includes/nefo.admin.institutions');
module_load_include('inc', 'nefo', 'includes/nefo.search');

/**
 * @file
 * Internationalization (i18n) submodule: Multilingual NeFo categories
 */

/**
 * Implements hook_menu().
 *
 * Add translate tab to categories config.
 */
function i18n_nefo_intersubject_menu() {
  $items['admin/config/nefo/categories/intersubjects/%nefo_intersubject/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -100,
  );
  $items['admin/config/nefo/categories/intersubjects/%nefo_intersubject/translate'] = array(
    'title' => 'Translate',
    'access callback' => 'i18n_nefo_intersubject_translate_tab_access',
    'page callback' => 'i18n_string_object_translate_page',
    'page arguments' => array('nefo_intersubject', 5),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );
  $items['admin/config/nefo/categories/intersubjects/%nefo_intersubject/translate/%language'] = array(
    'title' => 'Translate',
    'access callback' => 'i18n_nefo_intersubject_translate_tab_access',
    'page callback' => 'i18n_string_object_translate_page',
    'page arguments' => array('nefo_intersubject', 5, 7),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Menu access callback function.
 */
function i18n_nefo_intersubject_translate_tab_access() {
  return user_access('administer nefo configuration');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function i18n_nefo_intersubject_form_nefo_admin_intersubject_delete_confirm_alter(&$form, &$form_state) {
  $form['#submit'][] = 'i18n_nefo_intersubject_form_nefo_admin_intersubject_delete_confirm_submit';
}

/**
 * Remove strings for deleted categories.
 */
function i18n_nefo_intersubject_form_nefo_admin_intersubject_delete_confirm_submit(&$form, $form_state) {
  $isid = $form['isid']['#value']['isid'];
  i18n_string_remove("nefo_intersubject:interdisciplinarysubject:$isid:name");
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function i18n_nefo_intersubject_form_nefo_admin_intersubject_form_alter(&$form, &$form_state) {
    $form['actions']['translate'] = array(
    '#type' => 'submit',
    '#name'   => 'save_translate',
    '#value' => t('Save and translate'),
  );
  $form['#submit'][] = 'i18n_nefo_intersubject_form_nefo_admin_intersubject_form_submit';
}

/**
 * Remove strings for edited/added interdisciplinary subject.
 */
function i18n_nefo_intersubject_form_nefo_admin_intersubject_form_submit($form, &$form_state) {
  $intersubject = $form_state['values'];
  i18n_string_update(array('nefo_intersubject', 'interdisciplinarysubject', $intersubject['isid'], 'name'), $intersubject['name']);
  if ($form_state['triggering_element']['#name'] == 'save_translate') {
    $form_state['redirect'] = 'admin/config/nefo/categories/intersubjects/' . $intersubject['isid'] . '/translate';
  }
}

